### ISSUE TITLE
3/20 회의결과 TODO LIST

### ISSUE THREAD

**Issue by blissray** [TeamLab/seminar#7]
3/20 회의결과 각 랩구성원들이 해야할 일들입니다.

- [ ] 논문 개요 작성 - @TeamLab/teamlab (~3/24)
- [ ] 발표자료 검토 - @seriLucute (~3/24)
- [ ] 챗봇 대화 구현 고민 - @SeongCheol-Kim (~3/24) 
- [ ] 논문 초안 작성 -  @TeamLab/teamlab  (~3/27)

**Comment by blissray** [comment]
담당자들은 종료후 체크해주세요.
